import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import {
  CHAT_GEN_TIMEOUT_MS,
  parseModelJson,
  runChatGenerationWith,
  type ChatMessage,
} from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * Anthropic Messages API adapter with prompt caching. Uses `ANTHROPIC_API_KEY`
 * from env. Default model `claude-sonnet-4-6`. Override via `ANTHROPIC_MODEL`.
 *
 * Always validates the model output via `AgentSpecSchema`. On any failure
 * (network, parse, schema, missing key) it throws so the caller knows the
 * real provider failed.
 */
@Injectable()
export class AnthropicLlmAdapter implements LlmAgentGenerator {
  readonly name = 'anthropic';
  private readonly logger = new Logger(AnthropicLlmAdapter.name);

  private get model(): string {
    return env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6';
  }

  private get client(): { apiKey: string; baseUrl: string } {
    const apiKey = env.ANTHROPIC_API_KEY;
    if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not set');
    return { apiKey, baseUrl: 'https://api.anthropic.com/v1' };
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = this.pickTemplate(input);
    const spec = await this.callModel(input, baseTemplate);
    const parsed = AgentSpecSchema.safeParse(spec);
    if (!parsed.success) {
      this.logger.warn(`Anthropic returned invalid Agent Spec: ${parsed.error.message}`);
      throw new Error(`Anthropic returned invalid Agent Spec: ${parsed.error.message}`);
    }
    return {
      spec: parsed.data,
      suggested_name: parsed.data.name,
      rationale: `Generated by Anthropic (${this.model}) seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0.`,
      matched_template_slug: baseTemplate.slug,
    };
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }
    return runChatGenerationWith(this.name, (messages) => this.callMessages(messages), input);
  }

  /**
   * Anthropic Messages API transport for chat generation. The shared engine
   * emits OpenAI-style messages; Anthropic requires system prompts in a
   * dedicated `system` field and a strictly alternating user/assistant list,
   * so system messages are hoisted and cached with prompt caching.
   */
  private async callMessages(messages: ChatMessage[]): Promise<unknown> {
    const { apiKey, baseUrl } = this.client;
    const systemText = messages
      .filter((m) => m.role === 'system')
      .map((m) => m.content)
      .join('\n\n');
    // Anthropic rejects adjacent same-role turns and empty message lists, so
    // merge consecutive same-role messages and require at least one turn.
    const turns = messages
      .filter((m) => m.role !== 'system')
      .reduce<Array<{ role: string; content: string }>>((acc, m) => {
        const last = acc.at(-1);
        if (last && last.role === m.role) {
          last.content = `${last.content}\n\n${m.content}`;
          return acc;
        }
        acc.push({ role: m.role, content: m.content });
        return acc;
      }, []);
    if (turns.length === 0) {
      throw new Error('Anthropic chat generation requires at least one user turn.');
    }

    const res = await fetch(`${baseUrl}/messages`, {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 8192,
        system: [
          {
            type: 'text',
            text: systemText,
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: turns,
      }),
      signal: AbortSignal.timeout(CHAT_GEN_TIMEOUT_MS),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`Anthropic API error ${res.status}: ${text.slice(0, 300)}`);
    }

    const json = (await res.json()) as { content: Array<{ type: string; text?: string }> };
    const text = json.content.find((c) => c.type === 'text')?.text ?? '';
    if (!text) throw new Error('Empty model response (no text content block).');
    return parseModelJson(text);
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const { apiKey, baseUrl } = this.client;
      const res = await fetch(`${baseUrl}/messages`, {
        method: 'POST',
        headers: {
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private async callModel(
    input: GenerateAgentDto,
    base: AgentTemplateSeed,
  ): Promise<unknown> {
    const { apiKey, baseUrl } = this.client;
    const baseSpec: AgentSpec = base.spec as AgentSpec;

    const res = await fetch(`${baseUrl}/messages`, {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 4096,
        system: [
          {
            type: 'text',
            text: this.buildSystemPrompt(),
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: [
          {
            role: 'user',
            content: this.buildUserPrompt(input, baseSpec),
          },
        ],
      }),
      signal: AbortSignal.timeout(60_000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`Anthropic API error ${res.status}: ${text.slice(0, 300)}`);
    }

    const json = (await res.json()) as {
      content: Array<{ type: string; text?: string }>;
    };
    const text = json.content.find((c) => c.type === 'text')?.text ?? '';
    return JSON.parse(text);
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type ∈ inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Do NOT include markdown fences. Output JSON only.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, baseSpec: AgentSpec): string {
    const ctx = input.business_context ?? {};
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      `Use the following template as the starting point and tailor it to the prompt:`,
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}
