import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import { MockAgentGeneratorService } from '../../agents/mock-generator.service';
import type { LlmAgentGenerator } from '../llm.provider.interface';

/**
 * Anthropic Messages API adapter. Uses `ANTHROPIC_API_KEY` from env.
 * Default model `claude-sonnet-4-6`. Override via `ANTHROPIC_MODEL`.
 *
 * Uses prompt caching on the system prompt to reduce cost on repeated
 * generations. Validates output against AgentSpecSchema and falls back
 * to the deterministic mock generator on any failure.
 */
@Injectable()
export class AnthropicLlmAdapter implements LlmAgentGenerator {
  readonly name = 'anthropic';
  private readonly logger = new Logger(AnthropicLlmAdapter.name);
  private readonly endpoint = 'https://api.anthropic.com/v1/messages';
  private readonly model: string;

  constructor(private readonly mock: MockAgentGeneratorService) {
    this.model = env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6';
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.ANTHROPIC_API_KEY) {
      this.logger.warn('ANTHROPIC_API_KEY not set — falling back to MockAgentGeneratorService.');
      return this.mock.generate(input);
    }

    const baseTemplate = this.pickTemplate(input);
    try {
      const spec = await this.callModel(input, baseTemplate);
      const parsed = AgentSpecSchema.safeParse(spec);
      if (!parsed.success) {
        this.logger.warn(`Anthropic returned invalid Agent Spec: ${parsed.error.message}`);
        return this.mock.generate(input);
      }
      return {
        spec: parsed.data,
        suggested_name: parsed.data.name,
        rationale: `Generated by Anthropic (${this.model}) seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0.`,
        matched_template_slug: baseTemplate.slug,
      };
    } catch (err) {
      this.logger.warn(`Anthropic call failed: ${(err as Error).message}. Falling back to mock.`);
      return this.mock.generate(input);
    }
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private async callModel(
    input: GenerateAgentDto,
    base: AgentTemplateSeed,
  ): Promise<unknown> {
    const res = await fetch(this.endpoint, {
      method: 'POST',
      headers: {
        'x-api-key': env.ANTHROPIC_API_KEY!,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 4096,
        temperature: 0.3,
        system: [
          {
            type: 'text',
            text: this.buildSystemPrompt(),
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: [
          {
            role: 'user',
            content: this.buildUserPrompt(input, base),
          },
        ],
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`HTTP ${res.status} ${res.statusText} — ${text.slice(0, 300)}`);
    }
    const json = (await res.json()) as {
      content?: Array<{ type: string; text?: string }>;
    };
    const text = json.content?.find((c) => c.type === 'text')?.text;
    if (!text) throw new Error('Empty model response (no text content block).');
    const cleaned = stripCodeFences(text);
    return JSON.parse(cleaned);
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract. No markdown, no commentary.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type ∈ inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Output a single JSON object.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, base: AgentTemplateSeed): string {
    const ctx = input.business_context ?? {};
    const baseSpec: AgentSpec = base.spec as AgentSpec;
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      'Use the following template as the starting point and tailor it to the prompt:',
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}

function stripCodeFences(s: string): string {
  const trimmed = s.trim();
  if (trimmed.startsWith('```')) {
    return trimmed.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/i, '').trim();
  }
  return trimmed;
}
