import { Injectable } from '@nestjs/common';
import {
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import {
  CHAT_GEN_TIMEOUT_MS,
  parseModelJson,
  pickTemplate,
  runAgentGenerationWith,
  runChatGenerationWith,
  type ChatMessage,
} from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * Anthropic Messages API adapter with prompt caching. Uses `ANTHROPIC_API_KEY`
 * from env. Default model `claude-sonnet-4-6`. Override via `ANTHROPIC_MODEL`.
 *
 * Validates the model output via `AgentSpecSchema` with one self-repair retry;
 * if it still fails, it falls back to the seed template instead of throwing.
 */
@Injectable()
export class AnthropicLlmAdapter implements LlmAgentGenerator {
  readonly name = 'anthropic';

  private get model(): string {
    return env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6';
  }

  private get client(): { apiKey: string; baseUrl: string } {
    const apiKey = env.ANTHROPIC_API_KEY;
    if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not set');
    return { apiKey, baseUrl: 'https://api.anthropic.com/v1' };
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = pickTemplate(input.template_slug);
    const { spec, usedFallback } = await runAgentGenerationWith(
      this.name,
      (messages) => this.callMessages(messages),
      input,
      baseTemplate,
    );
    return {
      spec,
      suggested_name: spec.name,
      rationale: usedFallback
        ? `Anthropic (${this.model}) output failed Agent Spec v1.0 validation after self-repair; fell back to template "${baseTemplate.name}".`
        : `Generated by Anthropic (${this.model}) seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0.`,
      matched_template_slug: baseTemplate.slug,
    };
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }
    return runChatGenerationWith(this.name, (messages) => this.callMessages(messages), input);
  }

  /**
   * Anthropic Messages API transport for chat generation. The shared engine
   * emits OpenAI-style messages; Anthropic requires system prompts in a
   * dedicated `system` field and a strictly alternating user/assistant list,
   * so system messages are hoisted and cached with prompt caching.
   */
  private async callMessages(messages: ChatMessage[]): Promise<unknown> {
    const { apiKey, baseUrl } = this.client;
    const systemText = messages
      .filter((m) => m.role === 'system')
      .map((m) => m.content)
      .join('\n\n');
    // Anthropic rejects adjacent same-role turns and empty message lists, so
    // merge consecutive same-role messages and require at least one turn.
    const turns = messages
      .filter((m) => m.role !== 'system')
      .reduce<Array<{ role: string; content: string }>>((acc, m) => {
        const last = acc.at(-1);
        if (last && last.role === m.role) {
          last.content = `${last.content}\n\n${m.content}`;
          return acc;
        }
        acc.push({ role: m.role, content: m.content });
        return acc;
      }, []);
    if (turns.length === 0) {
      throw new Error('Anthropic chat generation requires at least one user turn.');
    }

    const res = await fetch(`${baseUrl}/messages`, {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 8192,
        system: [
          {
            type: 'text',
            text: systemText,
            cache_control: { type: 'ephemeral' },
          },
        ],
        messages: turns,
      }),
      signal: AbortSignal.timeout(CHAT_GEN_TIMEOUT_MS),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`Anthropic API error ${res.status}: ${text.slice(0, 300)}`);
    }

    const json = (await res.json()) as { content: Array<{ type: string; text?: string }> };
    const text = json.content.find((c) => c.type === 'text')?.text ?? '';
    if (!text) throw new Error('Empty model response (no text content block).');
    return parseModelJson(text);
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const { apiKey, baseUrl } = this.client;
      const res = await fetch(`${baseUrl}/messages`, {
        method: 'POST',
        headers: {
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }
}
