import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import { LlmCacheService } from '../llm-cache.service';
import { runChatGeneration, type OpenAiCompatTarget } from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * Azure AI Foundry adapter (OpenAI-compatible chat completions).
 *
 * Works against the raw Foundry endpoint or a Cloudflare AI Gateway route in
 * front of it — `LLM_BASE_URL` decides. Auth is sent both as
 * `Authorization: Bearer` (Foundry v1 endpoints, AI Gateway) and `api-key`
 * (legacy Azure OpenAI deployments); each target ignores the header it does
 * not use. Default model deployment: `gpt-5.4-mini`.
 */
@Injectable()
export class AzureAiFoundryAdapter implements LlmAgentGenerator {
  readonly name = 'azure-aifoundry';
  private readonly logger = new Logger(AzureAiFoundryAdapter.name);
  private readonly endpoint: string;
  private readonly model: string;
  private readonly apiVersion = env.LLM_API_VERSION;

  constructor(private readonly cache: LlmCacheService) {
    // No default endpoint: an Azure resource URL is deployment-specific, so a
    // hardcoded fallback would silently send prompts to the wrong resource.
    // The adapter is constructed eagerly by the DI container even when another
    // provider is selected, so the throw is deferred to first use; the LLM
    // module factory and the production env check fail fast when this adapter
    // is actually selected without LLM_BASE_URL.
    this.endpoint = (env.LLM_BASE_URL ?? '').replace(/\/$/, '');
    this.model = env.LLM_MODEL ?? 'gpt-5.4-mini';
  }

  private completionsUrl(): string {
    if (!this.endpoint) {
      throw new Error(
        'LLM_BASE_URL is required when LLM_PROVIDER=azure-aifoundry (e.g. ' +
          'https://<resource>.openai.azure.com/openai/v1 or a Cloudflare AI Gateway azure-openai route).',
      );
    }
    const url = `${this.endpoint}/chat/completions`;
    return this.apiVersion ? `${url}?api-version=${this.apiVersion}` : url;
  }

  private authHeaders(): Record<string, string> {
    const key = env.LLM_API_KEY ?? '';
    return {
      Authorization: `Bearer ${key}`,
      'api-key': key,
    };
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    const cacheKey = this.cache.buildKey(input);
    const cached = await this.cache.get(cacheKey);
    if (cached) {
      this.logger.log(`[azure-aifoundry] Cache hit for prompt "${input.prompt.slice(0, 50)}..."`);
      return cached;
    }

    if (!env.LLM_API_KEY) {
      throw new Error('LLM_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = this.pickTemplate(input);
    const spec = await this.callModel(input, baseTemplate);
    const parsed = AgentSpecSchema.safeParse(spec);
    if (!parsed.success) {
      this.logger.warn(
        `[azure-aifoundry] Model returned invalid Agent Spec: ${parsed.error.message}`,
      );
      throw new Error(`Azure AI Foundry returned invalid Agent Spec: ${parsed.error.message}`);
    }

    const result: GenerateAgentResult = {
      spec: parsed.data,
      suggested_name: parsed.data.name,
      rationale: `Generated by Azure AI Foundry (${this.model}). Seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0. Cached for 24h.`,
      matched_template_slug: baseTemplate.slug,
    };

    await this.cache.set(cacheKey, result);
    this.logger.log(
      `[azure-aifoundry] Generated + cached agent spec for prompt "${input.prompt.slice(0, 50)}..."`,
    );
    return result;
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.LLM_API_KEY) {
      throw new Error('LLM_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }
    const target: OpenAiCompatTarget = {
      url: this.completionsUrl(),
      headers: this.authHeaders(),
      model: this.model,
      providerName: this.name,
      temperature: this.supportsTemperature() ? 0.3 : null,
    };
    return runChatGeneration(target, input);
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const res = await fetch(this.completionsUrl(), {
        method: 'POST',
        headers: {
          ...this.authHeaders(),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }

  private async callModel(input: GenerateAgentDto, base: AgentTemplateSeed): Promise<unknown> {
    const res = await fetch(this.completionsUrl(), {
      method: 'POST',
      headers: {
        ...this.authHeaders(),
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        ...(this.supportsTemperature() ? { temperature: 0.3 } : {}),
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: this.buildSystemPrompt() },
          { role: 'user', content: this.buildUserPrompt(input, base) },
        ],
      }),
      signal: AbortSignal.timeout(60_000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`HTTP ${res.status} ${res.statusText} \u2014 ${text.slice(0, 300)}`);
    }
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = json.choices?.[0]?.message?.content;
    if (!content) throw new Error('Empty model response (no choices[0].message.content).');

    let parsed: unknown;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`Non-JSON response from model: ${content.slice(0, 100)}`);
    }
    return parsed;
  }

  private supportsTemperature(): boolean {
    return !/^(?:gpt-5|o\d)/i.test(this.model);
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type \u2208 inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Do NOT include markdown fences. Output JSON only.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, base: AgentTemplateSeed): string {
    const ctx = input.business_context ?? {};
    const baseSpec: AgentSpec = base.spec as AgentSpec;
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      `Use the following template as the starting point and tailor it to the prompt:`,
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}
