import { Injectable, Logger } from '@nestjs/common';
import {
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import { LlmCacheService } from '../llm-cache.service';
import {
  openAiCompatCaller,
  pickTemplate,
  runAgentGenerationWith,
  runChatGeneration,
  type OpenAiCompatTarget,
} from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * Azure AI Foundry adapter (OpenAI-compatible chat completions).
 *
 * Works against the raw Foundry endpoint or a Cloudflare AI Gateway route in
 * front of it — `LLM_BASE_URL` decides. Auth is sent both as
 * `Authorization: Bearer` (Foundry v1 endpoints, AI Gateway) and `api-key`
 * (legacy Azure OpenAI deployments); each target ignores the header it does
 * not use. Default model deployment: `gpt-5.4-mini`.
 */
@Injectable()
export class AzureAiFoundryAdapter implements LlmAgentGenerator {
  readonly name = 'azure-aifoundry';
  private readonly logger = new Logger(AzureAiFoundryAdapter.name);
  private readonly endpoint: string;
  private readonly model: string;
  private readonly apiVersion = env.LLM_API_VERSION;

  constructor(private readonly cache: LlmCacheService) {
    // No default endpoint: an Azure resource URL is deployment-specific, so a
    // hardcoded fallback would silently send prompts to the wrong resource.
    // The adapter is constructed eagerly by the DI container even when another
    // provider is selected, so the throw is deferred to first use; the LLM
    // module factory and the production env check fail fast when this adapter
    // is actually selected without LLM_BASE_URL.
    this.endpoint = (env.LLM_BASE_URL ?? '').replace(/\/$/, '');
    this.model = env.LLM_MODEL ?? 'gpt-5.4-mini';
  }

  private completionsUrl(): string {
    if (!this.endpoint) {
      throw new Error(
        'LLM_BASE_URL is required when LLM_PROVIDER=azure-aifoundry (e.g. ' +
          'https://<resource>.openai.azure.com/openai/v1 or a Cloudflare AI Gateway azure-openai route).',
      );
    }
    const url = `${this.endpoint}/chat/completions`;
    return this.apiVersion ? `${url}?api-version=${this.apiVersion}` : url;
  }

  private authHeaders(): Record<string, string> {
    const key = env.LLM_API_KEY ?? '';
    return {
      Authorization: `Bearer ${key}`,
      'api-key': key,
    };
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    const cacheKey = this.cache.buildKey(input);
    const cached = await this.cache.get(cacheKey);
    if (cached) {
      this.logger.log(`[azure-aifoundry] Cache hit for prompt "${input.prompt.slice(0, 50)}..."`);
      return cached;
    }

    if (!env.LLM_API_KEY) {
      throw new Error('LLM_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = pickTemplate(input.template_slug);
    const { spec, usedFallback } = await runAgentGenerationWith(
      this.name,
      openAiCompatCaller({
        url: this.completionsUrl(),
        headers: this.authHeaders(),
        model: this.model,
        providerName: this.name,
        temperature: this.supportsTemperature() ? 0.3 : null,
      }),
      input,
      baseTemplate,
    );

    const result: GenerateAgentResult = {
      spec,
      suggested_name: spec.name,
      rationale: usedFallback
        ? `Azure AI Foundry (${this.model}) output failed Agent Spec v1.0 validation after self-repair; fell back to template "${baseTemplate.name}". Cached for 24h.`
        : `Generated by Azure AI Foundry (${this.model}). Seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0. Cached for 24h.`,
      matched_template_slug: baseTemplate.slug,
    };

    await this.cache.set(cacheKey, result);
    this.logger.log(
      `[azure-aifoundry] Generated + cached agent spec for prompt "${input.prompt.slice(0, 50)}..."`,
    );
    return result;
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.LLM_API_KEY) {
      throw new Error('LLM_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }
    const target: OpenAiCompatTarget = {
      url: this.completionsUrl(),
      headers: this.authHeaders(),
      model: this.model,
      providerName: this.name,
      temperature: this.supportsTemperature() ? 0.3 : null,
    };
    return runChatGeneration(target, input);
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const res = await fetch(this.completionsUrl(), {
        method: 'POST',
        headers: {
          ...this.authHeaders(),
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }

  private supportsTemperature(): boolean {
    return !/^(?:gpt-5|o\d)/i.test(this.model);
  }
}
