import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import { MockAgentGeneratorService } from '../../agents/mock-generator.service';
import { LlmCacheService } from '../llm-cache.service';
import type { LlmAgentGenerator } from '../llm.provider.interface';

@Injectable()
export class AzureAiFoundryAdapter implements LlmAgentGenerator {
  readonly name = 'azure-aifoundry';
  private readonly logger = new Logger(AzureAiFoundryAdapter.name);
  private readonly endpoint: string;
  private readonly model: string;
  private readonly apiVersion = env.LLM_API_VERSION ?? '2024-02-01';

  constructor(
    private readonly mock: MockAgentGeneratorService,
    private readonly cache: LlmCacheService,
  ) {
    const base = env.LLM_BASE_URL ?? 'https://deepak7238kgs-0666-resource.services.ai.azure.com/openai/v1';
    this.endpoint = base.replace(/\/$/, '');
    this.model = env.LLM_MODEL ?? 'kimi-2.6-flash';
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    const cacheKey = this.cache.buildKey(input);
    const cached = await this.cache.get(cacheKey);
    if (cached) {
      this.logger.log(`[azure-aifoundry] Cache hit for prompt "${input.prompt.slice(0, 50)}..."`);
      return cached;
    }

    if (!env.LLM_API_KEY) {
      this.logger.warn('[azure-aifoundry] LLM_API_KEY not set — falling back to MockAgentGeneratorService.');
      return this.mock.generate(input);
    }

    const baseTemplate = this.pickTemplate(input);

    try {
      const spec = await this.callModel(input, baseTemplate);
      const parsed = AgentSpecSchema.safeParse(spec);
      if (!parsed.success) {
        this.logger.warn(`[azure-aifoundry] Model returned invalid Agent Spec: ${parsed.error.message}`);
        return this.mock.generate(input);
      }

      const result: GenerateAgentResult = {
        spec: parsed.data,
        suggested_name: parsed.data.name,
        rationale: `Generated by Azure AI Foundry Kimi 2.6 (${this.model}). Seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0. Cached for 24h.`,
        matched_template_slug: baseTemplate.slug,
      };

      await this.cache.set(cacheKey, result);
      this.logger.log(`[azure-aifoundry] Generated + cached agent spec for prompt "${input.prompt.slice(0, 50)}..."`);
      return result;
    } catch (err) {
      this.logger.warn(`[azure-aifoundry] Call failed: ${(err as Error).message}. Falling back to mock.`);
      return this.mock.generate(input);
    }
  }

  private async callModel(input: GenerateAgentDto, base: AgentTemplateSeed): Promise<unknown> {
    const url = `${this.endpoint}/chat/completions?api-version=${this.apiVersion}`;

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'api-key': env.LLM_API_KEY!,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        temperature: 0.3,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: this.buildSystemPrompt() },
          { role: 'user', content: this.buildUserPrompt(input, base) },
        ],
      }),
      signal: AbortSignal.timeout(30_000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`HTTP ${res.status} ${res.statusText} — ${text.slice(0, 300)}`);
    }
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = json.choices?.[0]?.message?.content;
    if (!content) throw new Error('Empty model response (no choices[0].message.content).');

    let parsed: unknown;
    try {
      parsed = JSON.parse(content);
    } catch {
      throw new Error(`Non-JSON response from model: ${content.slice(0, 100)}`);
    }
    return parsed;
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type ∈ inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Do NOT include markdown fences. Output JSON only.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, base: AgentTemplateSeed): string {
    const ctx = input.business_context ?? {};
    const baseSpec: AgentSpec = base.spec as AgentSpec;
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      `Use the following template as the starting point and tailor it to the prompt:`,
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}