import { Injectable } from '@nestjs/common';
import {
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import {
  openAiCompatCaller,
  pickTemplate,
  runAgentGenerationWith,
  runChatGeneration,
} from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * GitHub Models adapter. Calls the public GitHub Models inference endpoint
 * with a GitHub PAT (scope `models:read`). Default model is
 * `openai/gpt-4o-mini` because it supports JSON mode and is cheap; override
 * via `LLM_MODEL`.
 *
 * Request shape mirrors the OpenAI Chat Completions API. Validates the result
 * via `AgentSpecSchema` with one self-repair retry; if it still fails, it falls
 * back to the seed template instead of throwing.
 */
@Injectable()
export class GithubModelsLlmAdapter implements LlmAgentGenerator {
  readonly name = 'github';
  private readonly endpoint: string;
  private readonly model: string;

  constructor() {
    this.endpoint = env.LLM_BASE_URL ?? 'https://models.github.ai/inference/chat/completions';
    this.model = env.LLM_MODEL ?? 'openai/gpt-4o-mini';
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.GITHUB_TOKEN) {
      throw new Error('GITHUB_TOKEN not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = pickTemplate(input.template_slug);
    const { spec, usedFallback } = await runAgentGenerationWith(
      this.name,
      openAiCompatCaller({
        url: this.endpoint,
        headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}` },
        model: this.model,
        providerName: this.name,
      }),
      input,
      baseTemplate,
    );

    return {
      spec,
      suggested_name: spec.name,
      rationale: usedFallback
        ? `GitHub Models (${this.model}) output failed Agent Spec v1.0 validation after self-repair; fell back to template "${baseTemplate.name}".`
        : `Generated by GitHub Models (${this.model}) using "${baseTemplate.name}" as the seed. Validated against AgentSpecSchema v1.0.`,
      matched_template_slug: baseTemplate.slug,
    };
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.GITHUB_TOKEN) {
      throw new Error('GITHUB_TOKEN not set. Set the key or switch LLM_PROVIDER.');
    }
    return runChatGeneration(
      {
        url: this.endpoint,
        headers: { 'Authorization': `Bearer ${env.GITHUB_TOKEN}` },
        model: this.model,
        providerName: this.name,
      },
      input,
    );
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const res = await fetch(this.endpoint, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${env.GITHUB_TOKEN ?? ''}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }
}
