import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import type { LlmAgentGenerator } from '../llm.provider.interface';

/**
 * GitHub Models adapter. Calls the public GitHub Models inference endpoint
 * with a GitHub PAT (scope `models:read`). Default model is
 * `openai/gpt-4o-mini` because it supports JSON mode and is cheap; override
 * via `LLM_MODEL`.
 *
 * Request shape mirrors the OpenAI Chat Completions API. The system prompt
 * pins the model to return a valid Agent Spec JSON (schema_version 1.0). We
 * always validate the result via `AgentSpecSchema` and, on any failure
 * (network, parse, schema), throw so the caller knows the real provider failed.
 */
@Injectable()
export class GithubModelsLlmAdapter implements LlmAgentGenerator {
  readonly name = 'github';
  private readonly logger = new Logger(GithubModelsLlmAdapter.name);
  private readonly endpoint: string;
  private readonly model: string;

  constructor() {
    this.endpoint = env.LLM_BASE_URL ?? 'https://models.github.ai/inference/chat/completions';
    this.model = env.LLM_MODEL ?? 'openai/gpt-4o-mini';
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.GITHUB_TOKEN) {
      throw new Error('GITHUB_TOKEN not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = this.pickTemplate(input);
    const spec = await this.callModel(input, baseTemplate);
    const parsed = AgentSpecSchema.safeParse(spec);
    if (!parsed.success) {
      this.logger.warn(`Model returned invalid Agent Spec: ${parsed.error.message}`);
      throw new Error(`GitHub Models returned invalid Agent Spec: ${parsed.error.message}`);
    }

    return {
      spec: parsed.data,
      suggested_name: parsed.data.name,
      rationale: `Generated by GitHub Models (${this.model}) using "${baseTemplate.name}" as the seed. Validated against AgentSpecSchema v1.0.`,
      matched_template_slug: baseTemplate.slug,
    };
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private async callModel(
    input: GenerateAgentDto,
    base: AgentTemplateSeed,
  ): Promise<unknown> {
    const systemPrompt = this.buildSystemPrompt();
    const userPrompt = this.buildUserPrompt(input, base);

    const res = await fetch(this.endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        temperature: 0.3,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`HTTP ${res.status} ${res.statusText} \u2014 ${text.slice(0, 300)}`);
    }

    const json = (await res.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const content = json.choices?.[0]?.message?.content;
    if (!content) throw new Error('Empty model response (no choices[0].message.content).');

    return JSON.parse(content);
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type \u2208 inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Do NOT include markdown fences. Output JSON only.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, base: AgentTemplateSeed): string {
    const ctx = input.business_context ?? {};
    const baseSpec: AgentSpec = base.spec as AgentSpec;
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      `Use the following template as the starting point and tailor it to the prompt:`,
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}
