import { Injectable } from '@nestjs/common';
import {
  type ChatGenerateResult,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import {
  openAiCompatCaller,
  pickTemplate,
  runAgentGenerationWith,
  runChatGeneration,
} from '../chat-generation';
import type { ChatGenerateInput, LlmAgentGenerator } from '../llm.provider.interface';

/**
 * OpenAI Chat Completions adapter. Uses `OPENAI_API_KEY` from env. Default
 * model `gpt-4o-mini` (cheap, JSON-mode capable). Override via `LLM_MODEL`.
 *
 * Validates the model output via `AgentSpecSchema` with one self-repair retry;
 * if it still fails, it falls back to the seed template instead of throwing.
 */
@Injectable()
export class OpenAiLlmAdapter implements LlmAgentGenerator {
  readonly name = 'openai';
  private readonly endpoint: string;
  private readonly model: string;

  constructor() {
    this.endpoint = env.LLM_BASE_URL ?? 'https://api.openai.com/v1/chat/completions';
    // OpenAI models do not carry the `openai/` namespace prefix used by GitHub Models.
    const raw = env.LLM_MODEL ?? 'gpt-4o-mini';
    this.model = raw.startsWith('openai/') ? raw.slice('openai/'.length) : raw;
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.OPENAI_API_KEY) {
      throw new Error('OPENAI_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }

    const baseTemplate = pickTemplate(input.template_slug);
    const { spec, usedFallback } = await runAgentGenerationWith(
      this.name,
      openAiCompatCaller({
        url: this.endpoint,
        headers: { Authorization: `Bearer ${env.OPENAI_API_KEY}` },
        model: this.model,
        providerName: this.name,
      }),
      input,
      baseTemplate,
    );
    return {
      spec,
      suggested_name: spec.name,
      rationale: usedFallback
        ? `OpenAI (${this.model}) output failed Agent Spec v1.0 validation after self-repair; fell back to template "${baseTemplate.name}".`
        : `Generated by OpenAI (${this.model}) seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0.`,
      matched_template_slug: baseTemplate.slug,
    };
  }

  async chatGenerate(input: ChatGenerateInput): Promise<ChatGenerateResult> {
    if (!env.OPENAI_API_KEY) {
      throw new Error('OPENAI_API_KEY not set. Set the key or switch LLM_PROVIDER.');
    }
    return runChatGeneration(
      {
        url: this.endpoint,
        headers: { 'Authorization': `Bearer ${env.OPENAI_API_KEY}` },
        model: this.model,
        providerName: this.name,
      },
      input,
    );
  }

  async healthCheck(): Promise<'ok' | 'unavailable'> {
    try {
      const res = await fetch(`${this.endpoint}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${env.OPENAI_API_KEY ?? ''}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: 'user', content: 'hi' }],
        }),
        signal: AbortSignal.timeout(1_000),
      });
      return res.ok ? 'ok' : 'unavailable';
    } catch {
      return 'unavailable';
    }
  }
}
