import { Injectable, Logger } from '@nestjs/common';
import {
  AgentSpecSchema,
  MVP_TEMPLATES,
  findTemplateBySlug,
  type AgentSpec,
  type AgentTemplateSeed,
  type GenerateAgentDto,
  type GenerateAgentResult,
} from '@voiceforge/shared';
import { env } from '../../config/env';
import { MockAgentGeneratorService } from '../../agents/mock-generator.service';
import type { LlmAgentGenerator } from '../llm.provider.interface';

/**
 * OpenAI Chat Completions adapter. Uses `OPENAI_API_KEY` from env. Default
 * model `gpt-4o-mini` (cheap, JSON-mode capable). Override via `LLM_MODEL`.
 *
 * Always validates the model output via `AgentSpecSchema`. On any failure
 * (network, parse, schema, missing key) it falls back to the deterministic
 * mock generator so the user still gets a working draft.
 */
@Injectable()
export class OpenAiLlmAdapter implements LlmAgentGenerator {
  readonly name = 'openai';
  private readonly logger = new Logger(OpenAiLlmAdapter.name);
  private readonly endpoint: string;
  private readonly model: string;

  constructor(private readonly mock: MockAgentGeneratorService) {
    this.endpoint = env.LLM_BASE_URL ?? 'https://api.openai.com/v1/chat/completions';
    // OpenAI models do not carry the `openai/` namespace prefix used by GitHub Models.
    const raw = env.LLM_MODEL ?? 'gpt-4o-mini';
    this.model = raw.startsWith('openai/') ? raw.slice('openai/'.length) : raw;
  }

  async generate(input: GenerateAgentDto): Promise<GenerateAgentResult> {
    if (!env.OPENAI_API_KEY) {
      this.logger.warn('OPENAI_API_KEY not set — falling back to MockAgentGeneratorService.');
      return this.mock.generate(input);
    }

    const baseTemplate = this.pickTemplate(input);
    try {
      const spec = await this.callModel(input, baseTemplate);
      const parsed = AgentSpecSchema.safeParse(spec);
      if (!parsed.success) {
        this.logger.warn(`OpenAI returned invalid Agent Spec: ${parsed.error.message}`);
        return this.mock.generate(input);
      }
      return {
        spec: parsed.data,
        suggested_name: parsed.data.name,
        rationale: `Generated by OpenAI (${this.model}) seeded with template "${baseTemplate.name}". Validated against AgentSpecSchema v1.0.`,
        matched_template_slug: baseTemplate.slug,
      };
    } catch (err) {
      this.logger.warn(`OpenAI call failed: ${(err as Error).message}. Falling back to mock.`);
      return this.mock.generate(input);
    }
  }

  private pickTemplate(input: GenerateAgentDto): AgentTemplateSeed {
    if (input.template_slug) {
      const direct = findTemplateBySlug(input.template_slug);
      if (direct) return direct;
    }
    return MVP_TEMPLATES[0]!;
  }

  private async callModel(
    input: GenerateAgentDto,
    base: AgentTemplateSeed,
  ): Promise<unknown> {
    const res = await fetch(this.endpoint, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        temperature: 0.3,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: this.buildSystemPrompt() },
          { role: 'user', content: this.buildUserPrompt(input, base) },
        ],
      }),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error(`HTTP ${res.status} ${res.statusText} — ${text.slice(0, 300)}`);
    }
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    const content = json.choices?.[0]?.message?.content;
    if (!content) throw new Error('Empty model response (no choices[0].message.content).');
    return JSON.parse(content);
  }

  private buildSystemPrompt(): string {
    return [
      'You are VoiceForge AI, a generator of provider-neutral voice agent specifications.',
      'Return ONLY a JSON object that satisfies the Agent Spec v1.0 contract.',
      'Required top-level keys: schema_version="1.0", name, industry, agent_type, language, voice, identity, goals, required_fields, conversation_rules, knowledge, tools, handoff, compliance, analytics.',
      'agent_type ∈ inbound_receptionist | outbound_reminder | outbound_qualifier | outbound_confirmation | outbound_survey.',
      'For outbound_* types, set compliance.consent_required_for_outbound=true and include a sensible allowed_call_window.',
      'handoff.enabled=true requires handoff.conditions[]>=1.',
      'voice.tone is required. identity.business_name and identity.agent_name are required.',
      'goals must be a non-empty string array. tools[] each need {name, description, requires_confirmation, input_schema:{type:"object",properties,required}}.',
      'Do NOT invent fields outside the schema. Do NOT include markdown fences. Output JSON only.',
    ].join('\n');
  }

  private buildUserPrompt(input: GenerateAgentDto, base: AgentTemplateSeed): string {
    const ctx = input.business_context ?? {};
    const baseSpec: AgentSpec = base.spec as AgentSpec;
    return [
      `User prompt: ${input.prompt}`,
      ctx.business_name ? `Business name: ${ctx.business_name}` : '',
      ctx.industry_hint ? `Industry hint: ${ctx.industry_hint}` : '',
      ctx.timezone ? `Timezone: ${ctx.timezone}` : '',
      input.knowledge_source_ids?.length
        ? `Attach these knowledge_source_ids on knowledge.source_ids: ${JSON.stringify(input.knowledge_source_ids)}`
        : '',
      `Use the following template as the starting point and tailor it to the prompt:`,
      JSON.stringify(baseSpec, null, 2),
    ]
      .filter(Boolean)
      .join('\n\n');
  }
}
