#!/usr/bin/env bash
# =============================================================================
# VoiceForge AI — VM Bootstrap Script
# =============================================================================
# Run this ON THE AZURE VM (once after Terraform provisioning) to:
#   1. Authenticate with Azure Managed Identity
#   2. Fetch secrets from Key Vault
#   3. Write .env file for Docker Compose
#   4. Clone/pull the repository (optional)
#   5. Start the stack
#
# Usage:
#   chmod +x scripts/vm-bootstrap.sh
#   export KEY_VAULT_NAME="voiceforgestagingkv"
#   export APP_NAME="voiceforge"
#   ./scripts/vm-bootstrap.sh
# =============================================================================
set -euo pipefail

KEY_VAULT_NAME="${KEY_VAULT_NAME:-}"
APP_NAME="${APP_NAME:-voiceforge}"
COMPOSE_DIR="/opt/${APP_NAME}"
ENV_FILE="${COMPOSE_DIR}/.env"

if [ -z "$KEY_VAULT_NAME" ]; then
  echo "❌ ERROR: Set KEY_VAULT_NAME environment variable."
  echo "   Example: export KEY_VAULT_NAME=voiceforgestagingkv"
  exit 1
fi

echo "🔐 Logging into Azure with VM Managed Identity..."
az login --identity --allow-no-subscriptions >/dev/null

echo "📥 Fetching secrets from Key Vault: ${KEY_VAULT_NAME}..."

get_secret() {
  local name="$1"
  az keyvault secret show --name "$name" --vault-name "$KEY_VAULT_NAME" --query value -o tsv 2>/dev/null || {
    echo "⚠️  Warning: secret '$name' not found in Key Vault." >&2
    echo ""
  }
}

DATABASE_URL=$(get_secret "database-url")
DIRECT_URL=$(get_secret "direct-url")
REDIS_URL=$(get_secret "redis-url")
APPINSIGHTS_CS=$(get_secret "appinsights-connection-string")

# =============================================================================
# Write .env file (runtime secrets ONLY — never baked into images)
# =============================================================================
echo "📝 Writing ${ENV_FILE}..."
mkdir -p "$COMPOSE_DIR"

cat > "$ENV_FILE" <<EOF
# VoiceForge AI — Production Runtime Environment
# Generated by vm-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

NODE_ENV=production
APP_VERSION=$(date +%Y%m%d.%H%M%S)

# Data Layer (Azure Managed Services)
DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DIRECT_URL}
REDIS_URL=${REDIS_URL}

# Observability
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS_CS}

# API Configuration
API_PORT=4000
ALLOWED_ORIGINS=http://localhost,https://localhost

# Feature Flags / Providers (set real values in Key Vault or here)
AUTH_PROVIDER=clerk
VOICE_PROVIDER=vapi
LLM_PROVIDER=openai
EMBEDDING_PROVIDER=openai

# Secrets (injected here for Docker Compose; in production, fetch each from KV)
JWT_SECRET=replace-me-with-kv-secret
ENCRYPTION_KEY=replace-me-with-kv-secret
CLERK_SECRET_KEY=replace-me-with-kv-secret
CLERK_PUBLISHABLE_KEY=replace-me-with-kv-secret
OPENAI_API_KEY=replace-me-with-kv-secret
VAPI_API_KEY=replace-me-with-kv-secret
STRIPE_SECRET_KEY=replace-me-with-kv-secret
STRIPE_WEBHOOK_SECRET=replace-me-with-kv-secret
EOF

chmod 600 "$ENV_FILE"
chown "$(logname 2>/dev/null || echo "$USER"):$(logname 2>/dev/null || echo "$USER")" "$ENV_FILE"

echo "✅ Bootstrap complete."
echo ""
echo "Next steps:"
echo "  1. Copy docker-compose.prod.yml to ${COMPOSE_DIR}/"
echo "  2. Copy infra/nginx/ config to ${COMPOSE_DIR}/infra/nginx/"
echo "  3. Authenticate Docker to GHCR: echo <PAT> | docker login ghcr.io -u <USER> --password-stdin"
echo "  4. cd ${COMPOSE_DIR} && docker compose -f docker-compose.prod.yml pull"
echo "  5. docker compose -f docker-compose.prod.yml up -d"
echo ""
echo "To update secrets later, edit/add them in Azure Key Vault and re-run this script."
